### ISSUE TITLE
복사버튼 클릭 시, 링크 복사 및 alert가 뜨지 않는 현상

### ISSUE THREAD

**Issue by bloomspes** [PURPLECODE-TEAM/developer-designer-type-indicator#42]
Background : 테스트 완료 후, 결과를 url 링크를 직접 복사하기 위해 CopyButton을 클릭 한 뒤에 발생.

issue : 다음 코드에서 발생함.

const CopyButton = () => {
  const handleClick = () => {
    navigator.clipboard
      .writeText(window.location.href) // url 복사가 안 됨
      .then(alert('결과 공유 링크가 복사되었습니다.')); // 복사가 되지 않으므로 클릭 시, 실행이 되지 않음
  };

Expected : click 이벤트 발생 시, alert()가 실행되어야 하며 결과에 대한 url이 정상적으로 복사가 되어야 함.

Actual : alert()가 실행되지 않음, 결과에 대한 url 또한 복사되지 않음

**Comment by juajang** [comment]
버그 제보 정말 감사합니다!! 아직 navigator.clipboard를 지원하지 않는 일부 브라우저들이 있어서 작동이 안된 것 같습니다. 
해당 문제는 수정되었습니다.
